name: Lint
on:
  push:
    branches:
      - develop
      - master
jobs:
  flake8 & mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lint.txt

      - name: Lint with flake8
        run: |
          flake8 ./app
      - name: Type-check with mypy
        run: |
          mypy ./app
